// Tägliche Quizfragen zu Körper & Training sowie „Fakt des Tages“.

export interface QuizQuestion {
  id: string
  topic: 'VO2max' | 'Erholung' | 'Kraft' | 'Hyrox' | 'Knie' | 'Physiologie' | 'Ernährung' | 'Schlaf'
  question: string
  options: string[]
  correct: number
  explanation: string
}

export const QUIZ: QuizQuestion[] = [
  {
    id: 'vo2-def',
    topic: 'VO2max',
    question: 'Was beschreibt die VO2max?',
    options: [
      'Die maximale Herzfrequenz',
      'Die maximale Sauerstoffmenge, die der Körper pro Minute aufnehmen und verwerten kann',
      'Den Sauerstoffgehalt im Blut in Ruhe',
      'Die Laktatmenge bei Erschöpfung',
    ],
    correct: 1,
    explanation: 'Angegeben meist in ml Sauerstoff pro kg Körpergewicht pro Minute (ml/kg/min). Sie ist einer der stärksten Prädiktoren für Langlebigkeit.',
  },
  {
    id: 'vo2-4x4',
    topic: 'VO2max',
    question: 'Wie sieht das klassische norwegische 4×4-Intervall aus?',
    options: [
      '4 × 4 min bei 90–95 % HFmax mit 3 min aktiver Pause',
      '4 × 4 Sprints à 4 Sekunden',
      '4 Stunden im Zone-2-Bereich',
      '4 × 4 km im Wettkampftempo',
    ],
    correct: 0,
    explanation: 'Das Protokoll aus Trondheim (NTNU) zeigte in Studien deutliche VO2max-Steigerungen. Die Pause ist locker aktiv (ca. 60–70 % HFmax).',
  },
  {
    id: 'vo2-modality',
    topic: 'VO2max',
    question: 'Muss man laufen, um die VO2max zu verbessern?',
    options: [
      'Ja, nur Laufen wirkt auf die VO2max',
      'Nein – Rad, Rudern, SkiErg oder Schwimmen funktionieren auch, wenn die Intensität hoch genug ist',
      'Nein, dafür reicht Krafttraining',
      'Ja, aber nur bergauf',
    ],
    correct: 1,
    explanation: 'Entscheidend ist, dass Herz-Kreislauf-System lange genug nahe am Maximum arbeitet. Viel Muskelmasse (Rudern, SkiErg + Beine) hilft, die Herzfrequenz hoch zu bekommen.',
  },
  {
    id: 'vo2-time',
    topic: 'VO2max',
    question: 'Welche Zeit pro Woche nahe der VO2max (>90 % HFmax) gilt als guter Richtwert für Verbesserungen?',
    options: ['ca. 2 Minuten', 'ca. 10–20 Minuten, verteilt auf 1–2 Einheiten', 'mindestens 2 Stunden', 'Jeden Tag 60 Minuten'],
    correct: 1,
    explanation: 'Mit 2 Intervalleinheiten (z. B. 4×4) sammelt man ~10–16 min im Zielbereich. Mehr ist nicht automatisch besser – Erholung ist Teil des Reizes.',
  },
  {
    id: 'hr-lag',
    topic: 'Physiologie',
    question: 'Warum steigt die Herzfrequenz im Intervall erst nach 1–2 Minuten auf den Zielwert?',
    options: [
      'Weil die Pulsuhr verzögert misst',
      'Weil sich das Herz-Kreislauf-System verzögert an die Belastung anpasst (HF-Drift/Trägheit)',
      'Weil man zu langsam startet',
      'Weil Sauerstoff erst getrunken werden muss',
    ],
    correct: 1,
    explanation: 'Deshalb bringen 4-Minuten-Intervalle mehr Zeit nahe der VO2max als 1-Minuten-Intervalle – oder man nutzt 30/30-Serien, bei denen die HF hoch bleibt.',
  },
  {
    id: 'zone2',
    topic: 'Physiologie',
    question: 'Woran erkennst du grob, dass du in Zone 2 trainierst?',
    options: [
      'Du kannst kaum noch sprechen',
      'Du kannst in ganzen Sätzen sprechen, atmest aber merklich schneller',
      'Du schwitzt nicht',
      'Die Herzfrequenz liegt über 90 % HFmax',
    ],
    correct: 1,
    explanation: 'Zone 2 liegt etwa bei 60–70 % HFmax bzw. knapp unter der ersten Laktatschwelle. Der „Talk-Test“ ist eine praktische Kontrolle.',
  },
  {
    id: 'hrv',
    topic: 'Erholung',
    question: 'Was bedeutet eine im Vergleich zu deinem Durchschnitt deutlich niedrigere HRV am Morgen meist?',
    options: [
      'Der Körper ist besonders gut erholt',
      'Das autonome Nervensystem ist unter Stress – Belastung eher reduzieren',
      'Man sollte heute ein Maximaltest machen',
      'Die Uhr ist kaputt',
    ],
    correct: 1,
    explanation: 'Einzelwerte schwanken, aber ein Abfall gegenüber deiner persönlichen Baseline (z. B. 7-Tage-Schnitt) ist ein Signal für Stress, Infekt, Alkohol oder Schlafmangel.',
  },
  {
    id: 'rhr',
    topic: 'Erholung',
    question: 'Dein Ruhepuls ist heute 7 Schläge höher als üblich. Was ist eine sinnvolle Reaktion?',
    options: [
      'Extra hart trainieren, um ihn wieder zu senken',
      'Intensität reduzieren und auf Anzeichen eines Infekts achten',
      'Ignorieren, Ruhepuls sagt nichts aus',
      'Koffein trinken',
    ],
    correct: 1,
    explanation: 'Ein erhöhter Ruhepuls kann auf unvollständige Erholung, Hitze, Alkohol, Stress oder einen beginnenden Infekt hinweisen.',
  },
  {
    id: 'temp',
    topic: 'Erholung',
    question: 'Oura zeigt eine Körpertemperatur-Abweichung von +0,8 °C. Was ist klug?',
    options: [
      'Intervalltraining – der Körper ist warm',
      'Nur locker bewegen oder pausieren, auf Krankheitssymptome achten',
      'Sauna, um es rauszuschwitzen',
      'Nichts – Temperatur ist irrelevant',
    ],
    correct: 1,
    explanation: 'Eine deutliche Temperaturerhöhung ist eines der frühesten Infekt-Signale. Intensives Training kann eine Erkrankung verschlimmern.',
  },
  {
    id: 'supercomp',
    topic: 'Erholung',
    question: 'Wann wirst du eigentlich fitter?',
    options: ['Während der harten Einheit', 'In der Erholung nach der Einheit', 'Nur im Schlaf vor dem Training', 'Beim Aufwärmen'],
    correct: 1,
    explanation: 'Training setzt den Reiz, die Anpassung (Superkompensation) passiert in der Erholung – deshalb sind Recovery-Tage Teil des Plans.',
  },
  {
    id: 'polarized',
    topic: 'Physiologie',
    question: 'Was beschreibt das „polarisierte“ Trainingsmodell?',
    options: [
      'Jede Einheit mittelhart',
      'Ca. 80 % locker, ca. 20 % hart – wenig im mittleren Bereich',
      '50 % Kraft, 50 % Ausdauer',
      'Nur Intervalle',
    ],
    correct: 1,
    explanation: 'Viele Ausdauersportler trainieren so: viel lockere Grundlage, gezielt harte Intervalle. Mittelharte „graue Zone“ ermüdet stark bei geringerem Zusatznutzen.',
  },
  {
    id: 'hyrox-format',
    topic: 'Hyrox',
    question: 'Wie ist ein Hyrox-Rennen aufgebaut?',
    options: [
      '8 × 1 km Laufen, jeweils gefolgt von einer Workout-Station',
      '10 km Laufen, dann 8 Stationen',
      '4 Stationen und 4 km Rudern',
      'Ein Crossfit-WOD über 20 Minuten',
    ],
    correct: 0,
    explanation: 'Stationen: SkiErg 1000 m, Sled Push, Sled Pull, Burpee Broad Jumps, Rudern 1000 m, Farmers Carry, Sandbag Lunges, Wall Balls.',
  },
  {
    id: 'hyrox-running',
    topic: 'Hyrox',
    question: 'Welcher Anteil der Hyrox-Gesamtzeit entfällt bei den meisten Teilnehmern ungefähr auf das Laufen?',
    options: ['ca. 10 %', 'ca. 50 % oder mehr', 'ca. 90 %', 'Es gibt kein Laufen'],
    correct: 1,
    explanation: 'Die 8 km Laufen machen oft etwa die Hälfte der Zeit aus. Wer das Knie schonen muss, trainiert die Grundlage auf Ergometern und läuft gezielt, dosiert.',
  },
  {
    id: 'hyrox-compromised',
    topic: 'Hyrox',
    question: 'Was bedeutet „Compromised Running“ im Hyrox-Training?',
    options: [
      'Laufen mit schlechter Technik',
      'Laufen direkt nach einer ermüdenden Station',
      'Laufen auf dem Laufband',
      'Barfußlaufen',
    ],
    correct: 1,
    explanation: 'Im Rennen läufst du immer vorermüdet. Kniefreundliche Variante: statt Laufen z. B. Rad oder Rudern direkt nach der Station.',
  },
  {
    id: 'wallball',
    topic: 'Hyrox',
    question: 'Wie viele Wall Balls sind im Hyrox-Einzelrennen am Ende zu absolvieren?',
    options: ['50', '75', '100', '150'],
    correct: 2,
    explanation: '100 Wall Balls (Männer Open 6 kg, Ziel 3 m). Tipp fürs Knie: Box-Squat-Variante im Training, um die Tiefe zu kontrollieren.',
  },
  {
    id: 'sled',
    topic: 'Hyrox',
    question: 'Was ist beim Sled Push technisch am wichtigsten?',
    options: [
      'Aufrecht stehen und mit den Armen schieben',
      'Niedriger Körperwinkel, Arme fast gestreckt, kurze kraftvolle Schritte',
      'Möglichst große Schritte',
      'Anlauf nehmen und springen',
    ],
    correct: 1,
    explanation: 'Der Körper bildet eine Linie, die Kraft kommt aus Hüfte und Beinen. Sled Push ist konzentrisch – ohne Abbremsen – und deshalb meist recht kniefreundlich.',
  },
  {
    id: 'spanish-squat',
    topic: 'Knie',
    question: 'Warum werden isometrische Übungen wie der Spanish Squat bei Patellasehnen-Beschwerden eingesetzt?',
    options: [
      'Weil sie die Sehne komplett entlasten',
      'Weil sie die Sehne belasten ohne Bewegung und oft kurzfristig schmerzlindernd wirken',
      'Weil sie nur den Oberkörper trainieren',
      'Weil sie Sprünge ersetzen',
    ],
    correct: 1,
    explanation: 'Isometrische Halteübungen (z. B. 5 × 45 s) können Schmerzen reduzieren und die Sehne gezielt belasten. Bei anhaltenden Beschwerden: Physio abklären lassen.',
  },
  {
    id: 'knee-pain-rule',
    topic: 'Knie',
    question: 'Welche Schmerz-Faustregel wird in der Reha oft für Belastung genutzt?',
    options: [
      'Schmerz immer ignorieren',
      'Bis ca. 3–4/10 während der Übung ist ok, wenn es bis zum nächsten Morgen wieder auf Ausgangsniveau ist',
      'Jeder Schmerz bedeutet sofort aufhören',
      'Schmerz über 8/10 zeigt Fortschritt',
    ],
    correct: 1,
    explanation: 'Das „Schmerz-Monitoring-Modell“ erlaubt moderate, schnell abklingende Beschwerden. Wird es am Folgetag schlechter, war die Belastung zu hoch.',
  },
  {
    id: 'vmo',
    topic: 'Knie',
    question: 'Welche Muskelgruppe hilft besonders, das Knie beim Landen und Abstoppen (z. B. im Padel) seitlich zu stabilisieren?',
    options: ['Bizeps', 'Hüftabduktoren/Gesäßmuskulatur', 'Brustmuskulatur', 'Unterarmmuskeln'],
    correct: 1,
    explanation: 'Eine starke Hüfte (Glute medius) verhindert, dass das Knie nach innen fällt (Valgus). Übungen: Monster-Walks, Seitstütz mit Abduktion, Step-Downs.',
  },
  {
    id: 'cycling-knee',
    topic: 'Knie',
    question: 'Warum ist Radfahren für viele Knieprobleme gut verträglich?',
    options: [
      'Weil das Knie dabei nicht gebeugt wird',
      'Weil es keine Stoßbelastung gibt und die Last gut dosierbar ist',
      'Weil nur die Arme arbeiten',
      'Weil es kürzer dauert',
    ],
    correct: 1,
    explanation: 'Keine Landung, gleichmäßige zyklische Bewegung. Wichtig: richtige Sattelhöhe – zu tief belastet die Kniescheibe stärker.',
  },
  {
    id: 'protein',
    topic: 'Ernährung',
    question: 'Welche Proteinmenge pro Tag wird für Kraft-/Ausdauersportler häufig empfohlen?',
    options: ['0,3 g/kg', 'ca. 1,6–2,2 g/kg Körpergewicht', '5 g/kg', 'Protein ist nicht nötig'],
    correct: 1,
    explanation: 'Verteilt auf 3–5 Mahlzeiten à ca. 0,3–0,4 g/kg unterstützt das Muskelaufbau und Erholung.',
  },
  {
    id: 'carbs-intervals',
    topic: 'Ernährung',
    question: 'Warum sind Kohlenhydrate vor harten Intervallen sinnvoll?',
    options: [
      'Weil Fett bei hoher Intensität der Hauptbrennstoff ist',
      'Weil bei hoher Intensität vor allem Glykogen (Kohlenhydrate) verbrannt wird',
      'Weil sie die HRV erhöhen',
      'Sind sie nicht',
    ],
    correct: 1,
    explanation: 'Je höher die Intensität, desto größer der Anteil der Kohlenhydrate an der Energiebereitstellung.',
  },
  {
    id: 'sleep-hgh',
    topic: 'Schlaf',
    question: 'In welcher Schlafphase wird ein Großteil des Wachstumshormons ausgeschüttet?',
    options: ['REM-Schlaf', 'Tiefschlaf', 'Leichtschlaf', 'Wachphase'],
    correct: 1,
    explanation: 'Tiefschlaf (vor allem in der ersten Nachthälfte) ist zentral für körperliche Regeneration. Spätes Essen und Alkohol reduzieren ihn.',
  },
  {
    id: 'sleep-alcohol',
    topic: 'Schlaf',
    question: 'Wie wirkt Alkohol am Abend typischerweise auf HRV und Ruhepuls in der Nacht?',
    options: ['HRV hoch, Puls runter', 'HRV runter, Ruhepuls hoch', 'Keine Wirkung', 'Nur die Temperatur sinkt'],
    correct: 1,
    explanation: 'Das siehst du oft direkt in den Oura-Daten: niedrigere HRV, höherer Ruhepuls, schlechterer Readiness-Score.',
  },
  {
    id: 'sleep-need',
    topic: 'Schlaf',
    question: 'Wie viel Schlaf wird Erwachsenen, die viel trainieren, meist empfohlen?',
    options: ['5–6 Stunden', '7–9 Stunden', '10–12 Stunden', 'So wenig wie möglich'],
    correct: 1,
    explanation: 'Schlafmangel verschlechtert Reaktionszeit, Glukosestoffwechsel und erhöht das Verletzungsrisiko.',
  },
  {
    id: 'mito',
    topic: 'Physiologie',
    question: 'Was verbessert Zone-2-Training vor allem?',
    options: [
      'Die maximale Sprintkraft',
      'Mitochondrienfunktion und Fettstoffwechsel',
      'Die Knochendichte der Arme',
      'Die Reaktionszeit',
    ],
    correct: 1,
    explanation: 'Mehr und effizientere Mitochondrien verbessern die Ausdauergrundlage – die Basis, auf der VO2max-Intervalle aufbauen.',
  },
  {
    id: 'stroke-volume',
    topic: 'Physiologie',
    question: 'Welcher Faktor trägt beim Training am meisten zur VO2max-Steigerung bei?',
    options: ['Größere Lunge', 'Höheres Schlagvolumen des Herzens', 'Schnellere Atmung', 'Mehr Körpergewicht'],
    correct: 1,
    explanation: 'Das Herz pumpt pro Schlag mehr Blut. Die maximale Herzfrequenz selbst ändert sich durch Training kaum.',
  },
  {
    id: 'hrmax-formula',
    topic: 'Physiologie',
    question: 'Wie genau ist die Formel „220 minus Alter“ für die maximale Herzfrequenz?',
    options: [
      'Sehr genau (±1 Schlag)',
      'Grob – Abweichungen von 10–15 Schlägen sind häufig',
      'Sie gilt nur für Frauen',
      'Sie ist genauer als ein Test',
    ],
    correct: 1,
    explanation: 'Besser: HFmax aus harten Einheiten der Garmin-Daten ablesen oder in den Einstellungen selbst eintragen.',
  },
  {
    id: 'strength-endurance',
    topic: 'Kraft',
    question: 'Schadet Krafttraining der Ausdauerleistung?',
    options: [
      'Ja, immer',
      'Nein – richtig dosiert verbessert es Laufökonomie, Verletzungsresistenz und Hyrox-Stationen',
      'Nur bei Frauen',
      'Nur wenn man es morgens macht',
    ],
    correct: 1,
    explanation: 'Der „Interferenz-Effekt“ ist bei vernünftiger Planung klein. Harte Kraft- und Intervalltage möglichst trennen oder mit einigen Stunden Abstand.',
  },
  {
    id: 'rir',
    topic: 'Kraft',
    question: 'Was bedeutet „2 RIR“ bei einem Kraftsatz?',
    options: ['2 Runden in Reserve', '2 Wiederholungen hätten noch gehen können', '2 Minuten Pause', '2 Sätze bis zum Versagen'],
    correct: 1,
    explanation: 'Reps in Reserve – eine einfache Art, die Intensität zu steuern, ohne ständig bis zum Muskelversagen zu gehen.',
  },
  {
    id: 'eccentric',
    topic: 'Kraft',
    question: 'Warum hilft exzentrisches Training (z. B. Nordic Hamstring Curl) gegen Verletzungen?',
    options: [
      'Es trainiert nur die Ausdauer',
      'Es stärkt den Muskel in der verlängerten Position, in der er beim Abbremsen belastet wird',
      'Es macht beweglicher, aber nicht stärker',
      'Es ersetzt das Aufwärmen',
    ],
    correct: 1,
    explanation: 'Im Padel wird ständig abgebremst und die Richtung gewechselt – exzentrische Kraft schützt Oberschenkelrückseite und Knie.',
  },
  {
    id: 'lactate',
    topic: 'Physiologie',
    question: 'Ist Laktat die Ursache für Muskelkater?',
    options: [
      'Ja, es bleibt tagelang im Muskel',
      'Nein – Laktat ist nach ca. 30–60 min abgebaut; Muskelkater entsteht durch Mikroverletzungen',
      'Ja, aber nur beim Laufen',
      'Laktat gibt es im Körper nicht',
    ],
    correct: 1,
    explanation: 'Laktat ist sogar ein wichtiger Energieträger, den Herz und Muskeln verwerten.',
  },
  {
    id: 'deload',
    topic: 'Erholung',
    question: 'Was ist eine „Deload-Woche“?',
    options: [
      'Eine Woche ohne jede Bewegung',
      'Eine geplante Woche mit reduziertem Umfang/Intensität, meist alle 3–6 Wochen',
      'Eine Woche nur mit Intervallen',
      'Eine Diät-Woche',
    ],
    correct: 1,
    explanation: 'Reduziert kumulierte Ermüdung, damit die Anpassungen „durchkommen“.',
  },
  {
    id: 'body-battery',
    topic: 'Erholung',
    question: 'Was fließt in die Garmin Body Battery ein?',
    options: [
      'Nur die Schrittzahl',
      'HRV, Stress, Schlaf und Aktivität',
      'Nur der Akkustand der Uhr',
      'Das Körpergewicht',
    ],
    correct: 1,
    explanation: 'Sie wird tagsüber durch Stress und Aktivität entladen und nachts durch erholsamen Schlaf geladen.',
  },
  {
    id: 'breathing',
    topic: 'Erholung',
    question: 'Welche Atemtechnik aktiviert das parasympathische (Erholungs-)Nervensystem besonders?',
    options: ['Schnelle Brustatmung', 'Langsame Atmung mit verlängerter Ausatmung (z. B. 4 s ein, 6–8 s aus)', 'Luft anhalten bis zum Limit', 'Hyperventilieren'],
    correct: 1,
    explanation: 'Eine lange Ausatmung verstärkt die Vagus-Aktivität – ideal nach dem Training oder vor dem Schlafen.',
  },
  {
    id: 'padel-demands',
    topic: 'Physiologie',
    question: 'Welche Belastung ist für Padel typisch?',
    options: [
      'Gleichmäßige Dauerbelastung wie beim Marathon',
      'Intermittierend: kurze intensive Aktionen mit vielen Richtungswechseln und kurzen Pausen',
      'Reine Maximalkraft',
      'Hauptsächlich Stehen',
    ],
    correct: 1,
    explanation: 'Ballwechsel dauern oft 10–20 s. Eine gute aerobe Basis hilft, zwischen den Ballwechseln schneller zu erholen.',
  },
  {
    id: 'caffeine',
    topic: 'Ernährung',
    question: 'Wie lange ist die Halbwertszeit von Koffein ungefähr?',
    options: ['30 Minuten', '5–6 Stunden', '24 Stunden', '2 Tage'],
    correct: 1,
    explanation: 'Ein Kaffee um 16 Uhr ist um 22 Uhr noch zur Hälfte aktiv – das kann Tiefschlaf und HRV verschlechtern.',
  },
  {
    id: 'hydration',
    topic: 'Ernährung',
    question: 'Ab welchem Flüssigkeitsverlust (bezogen aufs Körpergewicht) sinkt die Ausdauerleistung messbar?',
    options: ['0,1 %', 'ca. 2 %', '10 %', 'Nie'],
    correct: 1,
    explanation: 'Bei 80 kg sind das schon 1,6 Liter – bei einem Padel-Match im Sommer schnell erreicht.',
  },
  {
    id: 'vo2-longevity',
    topic: 'VO2max',
    question: 'Was zeigen große Beobachtungsstudien zum Zusammenhang von Fitness (VO2max) und Sterblichkeit?',
    options: [
      'Kein Zusammenhang',
      'Höhere kardiorespiratorische Fitness geht mit deutlich geringerer Gesamtsterblichkeit einher',
      'Fitte Menschen leben kürzer',
      'Nur Rauchen ist relevant',
    ],
    correct: 1,
    explanation: 'In Studien (z. B. Mandsager et al., 2018) war niedrige Fitness ein ähnlich starker Risikofaktor wie Rauchen oder Diabetes.',
  },
]

export const FACTS: { text: string; topic: string }[] = [
  { topic: 'Padel', text: 'Padel wurde 1969 in Acapulco (Mexiko) von Enrique Corcuera erfunden – er baute Mauern um seinen Tennisplatz, weil ihm der Platz fehlte.' },
  { topic: 'Padel', text: 'Ein Padel-Court ist 20 × 10 m groß – etwa ein Drittel der Fläche eines Tennisplatzes.' },
  { topic: 'Padel', text: 'Die Netzhöhe beträgt in der Mitte 88 cm und an den Seiten 92 cm.' },
  { topic: 'Padel', text: 'Padel-Bälle haben etwas weniger Innendruck als Tennisbälle – dadurch springen sie niedriger und das Spiel wird kontrollierbarer.' },
  { topic: 'Padel', text: 'Der Aufschlag im Padel muss unterhalb der Hüfte getroffen werden und nach dem Aufsprung im diagonalen Aufschlagfeld landen.' },
  { topic: 'Padel', text: 'Die Rückwände sind 4 m hoch (3 m Glas + 1 m Gitter), damit der Ball im Spiel bleibt und Rallyes länger werden.' },
  { topic: 'Padel', text: 'Spanien gilt als Padel-Hochburg: Dort gibt es mehrere Millionen aktive Spielerinnen und Spieler und über 15.000 Courts.' },
  { topic: 'Padel', text: 'Der „Vibora“-Schlag heißt übersetzt „Viper“ – wegen der seitlichen, giftigen Schnittbewegung.' },
  { topic: 'Padel', text: 'Beim „Punto de oro“ (Golden Point) entscheidet bei 40:40 ein einziger Punkt – das Rückschlagteam wählt die Seite.' },
  { topic: 'Körper', text: 'Das Herz eines trainierten Ausdauersportlers kann in Ruhe unter 50 Mal pro Minute schlagen – weil es pro Schlag mehr Blut pumpt.' },
  { topic: 'Körper', text: 'Das Herz pumpt in Ruhe ca. 5 Liter Blut pro Minute, bei Maximalbelastung bei trainierten Menschen über 25 Liter.' },
  { topic: 'Körper', text: 'Die Patellasehne kann ein Vielfaches des Körpergewichts aushalten – bei Sprunglandungen wirken Kräfte von mehreren tausend Newton.' },
  { topic: 'Körper', text: 'Sehnen passen sich langsamer an als Muskeln: Muskelkraft steigt in Wochen, Sehnensteifigkeit braucht eher Monate.' },
  { topic: 'Körper', text: 'Die VO2max sinkt ohne Training ab etwa 30 Jahren um rund 10 % pro Jahrzehnt – mit Training lässt sich dieser Verlust stark bremsen.' },
  { topic: 'Körper', text: 'Mitochondrien haben ihre eigene DNA – sie stammen evolutionär von Bakterien ab.' },
  { topic: 'Körper', text: 'Der Körper hat rund 650 Skelettmuskeln; der größte ist der Gluteus maximus.' },
  { topic: 'Körper', text: 'Die Glykogenspeicher in Muskeln und Leber fassen zusammen etwa 400–600 g Kohlenhydrate – genug für ca. 90 Minuten intensive Belastung.' },
  { topic: 'Körper', text: 'Muskelkater (DOMS) erreicht sein Maximum meist 24–72 Stunden nach ungewohnter Belastung – besonders nach exzentrischen Bewegungen.' },
  { topic: 'Körper', text: 'Die Herzratenvariabilität (HRV) ist bei jedem Menschen anders – vergleiche dich nur mit deiner eigenen Baseline.' },
  { topic: 'Training', text: 'In einer Studie verbesserten untrainierte Erwachsene ihre VO2max mit 4×4-Intervallen 3× pro Woche um rund 10 % in 8 Wochen.' },
  { topic: 'Training', text: 'Norwegische Ausdauerathleten trainieren oft „Double Threshold“: zwei Schwellen-Einheiten an einem Tag, dafür viel ruhige Grundlage.' },
  { topic: 'Training', text: 'Beim Rudern arbeiten ca. 85 % der Muskulatur mit – ideal für hohe Herzfrequenzen ohne Stoßbelastung fürs Knie.' },
  { topic: 'Training', text: 'Isometrische Übungen können Blutdruck senken: Wall-Sits und Planks zeigten in Metaanalysen deutliche Effekte.' },
  { topic: 'Training', text: 'Schon ca. 150 Minuten moderate Bewegung pro Woche senken das Risiko für Herz-Kreislauf-Erkrankungen deutlich.' },
  { topic: 'Training', text: 'Nach einem harten Intervalltraining bleibt der Sauerstoffverbrauch noch Stunden erhöht (EPOC – „Nachbrenneffekt“).' },
  { topic: 'Training', text: 'Aufwärmen erhöht die Muskeltemperatur – pro Grad steigt die Muskelleistung um einige Prozent.' },
  { topic: 'Hyrox', text: 'Hyrox wurde 2017 in Hamburg gegründet und ist heute in vielen Ländern mit hunderttausenden Teilnehmenden pro Saison vertreten.' },
  { topic: 'Hyrox', text: 'Die Hyrox-Distanzen sind weltweit identisch – deshalb gibt es eine globale Bestenliste.' },
  { topic: 'Hyrox', text: 'Beim Sled Pull wird der Schlitten Hand über Hand am Seil gezogen – der Rücken und die Griffkraft sind oft der limitierende Faktor.' },
  { topic: 'Hyrox', text: 'Die „Roxzone“ ist der Wechselbereich zwischen Laufen und Stationen – viele verlieren dort unbemerkt Minuten.' },
  { topic: 'Schlaf', text: 'Nach einer Nacht mit nur ~4–5 Stunden Schlaf sinkt die Insulinsensitivität bei Gesunden messbar.' },
  { topic: 'Schlaf', text: 'Die Körperkerntemperatur muss abends um ca. 1 °C sinken, damit wir gut einschlafen – ein kühles Schlafzimmer (ca. 17–19 °C) hilft.' },
  { topic: 'Schlaf', text: 'Der meiste Tiefschlaf findet in den ersten 3–4 Stunden der Nacht statt, REM-Schlaf eher gegen Morgen.' },
  { topic: 'Schlaf', text: 'Oura misst die Temperatur an der Fingerhaut – Trends sind aussagekräftiger als absolute Werte.' },
  { topic: 'Ernährung', text: 'Nitrat aus Roter Bete kann die Sauerstoffkosten bei Belastung leicht senken – der Effekt ist bei Freizeitsportlern am größten.' },
  { topic: 'Ernährung', text: 'Koffein (ca. 3 mg/kg) etwa 45–60 min vor der Belastung ist eines der am besten belegten legalen Leistungsmittel.' },
  { topic: 'Ernährung', text: 'Kreatin ist eines der am besten untersuchten Supplemente – es unterstützt kurze, intensive Belastungen und Kraftzuwachs.' },
  { topic: 'Knie', text: 'Beim Radfahren wirkt nur ein Bruchteil der Gelenkkräfte, die beim Laufen auf das Knie einwirken – bei gleicher Herz-Kreislauf-Belastung.' },
  { topic: 'Knie', text: 'Eine schwache Hüftmuskulatur ist häufig mitverantwortlich für Knieschmerzen – das Knie „fällt“ dann bei Landungen nach innen.' },
  { topic: 'Knie', text: 'Beim Treppabgehen wirken auf das Kniegelenk Kräfte vom 3- bis 4-Fachen des Körpergewichts.' },
]
